# ☀️ Solar Energy Production
🇫🇷 **France — 2012 to 2026**

This notebook explores the relationship between meteorological conditions and solar energy production in France, using data from **RTE** (electricity transport network) and **Meteo-France** (weather data).

# ⬇️ 1. Modules imports & loading data

### &nbsp;&nbsp;&nbsp; A. Modules

In [1]:
# Imports for data
import numpy as np
import pandas as pd

# Imports for data visualization
import streamlit as st
import plotly.express as px 
import plotly.graph_objects as go

# Imports for machine learning
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import  OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

# Other
import scipy.stats as stats
import warnings
warnings.filterwarnings("ignore")

### &nbsp;&nbsp;&nbsp; C. Loading data

In [ ]:
# Loading dataset
PATH_RTE = 'data/rte.csv'
PATH_SOLAR = 'data/solar_prod.csv'

rte_df = pd.read_csv(PATH_RTE, sep=",", index_col=False, parse_dates=['Date'])
solar_df = pd.read_csv(PATH_SOLAR, sep=",", index_col=False, parse_dates=['date'])

In [6]:
rte_df

           Date   Solaire       TWh
0    2012-01-01    6255.0  0.003128
1    2012-01-02    4267.0  0.002133
2    2012-01-03    6768.0  0.003384
3    2012-01-04    8655.0  0.004327
4    2012-01-05    3207.0  0.001603
...         ...       ...       ...
5140 2026-01-27   46145.0  0.023072
5141 2026-01-28  131269.0  0.065634
5142 2026-01-29  124651.0  0.062325
5143 2026-01-30  135299.0  0.067650
5144 2026-01-31  121031.0  0.060515

[5145 rows x 3 columns]

In [7]:
solar_df

,date,snowfall,rainfall,daily_avg_temp,daily_avg_wind_speed,daily_avg_specific_humidity,atmospheric_radiation,visible_radiation,daily_avg_relative_humidity,total_evapotranspiration,...,snow_depth_6h,max_snow_depth,daily_avg_snow_cover_fraction,snowmelt_runoff,root_liquid_water,WGI_RACINE,min_temp,max_temp,solar,TWh
0,2012-01-01,0.0,10.1,13.1,4.9,8.503,3178.4,119.7,91.0,0.4,...,0.0,0.0,0.0,0.0,0.324,0.0,12.8,13.8,6255.0,0.003128
1,2012-01-02,0.0,1.0,8.3,3.5,5.646,2590.7,315.4,82.6,0.5,...,0.0,0.0,0.0,0.0,0.332,0.0,6.1,10.2,4267.0,0.002133
2,2012-01-03,0.0,2.0,9.8,6.0,6.429,2843.0,72.7,85.1,0.0,...,0.0,0.0,0.0,0.0,0.330,0.0,5.1,12.5,6768.0,0.003384
3,2012-01-04,0.0,0.1,8.9,4.7,5.010,2255.0,419.1,71.2,0.3,...,0.0,0.0,0.0,0.0,0.330,0.0,7.1,10.1,8655.0,0.004327
4,2012-01-05,0.0,1.8,10.5,7.9,5.915,2670.2,239.8,75.0,1.1,...,0.0,0.0,0.0,0.0,0.328,0.0,9.0,13.1,3207.0,0.001603
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5140,2026-01-27,0.0,9.2,7.2,3.6,5.725,2934.8,115.5,90.2,0.1,...,0.0,0.0,0.0,0.0,0.324,0.0,5.7,9.2,46145.0,0.023072
5141,2026-01-28,0.0,0.0,5.6,1.2,5.144,2693.8,356.3,91.6,0.4,...,0.0,0.0,0.0,0.0,0.332,0.0,3.6,8.7,131269.0,0.065634
5142,2026-01-29,0.0,2.7,3.1,2.2,4.513,2806.2,193.8,95.1,0.3,...,0.0,0.0,0.0,0.0,0.330,0.0,0.7,5.3,124651.0,0.062325
5143,2026-01-30,0.0,2.8,8.2,3.7,5.841,2735.6,240.1,87.2,0.0,...,0.0,0.0,0.0,0.0,0.332,0.0,4.8,12.0,135299.0,0.067650
5144,2026-01-31,0.0,0.0,7.1,2.3,5.788,2877.1,123.3,92.6,0.1,...,0.0,0.0,0.0,0.0,0.333,0.0,5.8,7.8,121031.0,0.060515